# Generated by Django 4.1 on 2022-11-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Fans',
        ),
    ]
