# Generated by Django 4.1 on 2022-11-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_App', '0002_rename_users_fans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fans',
            new_name='Fan',
        ),
    ]
